# Generated by Django 5.0.1 on 2024-01-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('spec', models.TextField()),
                ('doc_image', models.ImageField(default='default_image.jpg', upload_to='doctors')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kims.department')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('phone', models.CharField(default='', max_length=10, verbose_name='Phone')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='Email')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('booked_on', models.DateField(verbose_name='Booked On')),
                ('description', models.TextField(verbose_name='Description')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kims.department')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kims.doctor')),
            ],
        ),
    ]
