# Generated by Django 5.0.1 on 2024-01-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
