# Generated by Django 5.0.1 on 2024-01-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0004_alter_booking_booked_on_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
